# Generated by Django 3.1.2 on 2020-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticias_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('correo', models.TextField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('motivo', models.IntegerField()),
                ('respuesta', models.BooleanField()),
            ],
        ),
    ]
