# Generated by Django 3.1.2 on 2020-10-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='motivo',
            field=models.CharField(max_length=20),
        ),
    ]
