# Generated by Django 3.1.2 on 2020-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_auto_20201028_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
