# Generated by Django 3.1.2 on 2020-10-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_auto_20201028_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'permissions': (('editor', 'Es editor'), ('lector', 'Es lector'))},
        ),
    ]
