# Generated by Django 3.1.2 on 2020-10-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_auto_20201030_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='etiqueta',
            field=models.IntegerField(choices=[[0, 'Publico'], [1, 'Privado']]),
        ),
    ]
